In [7]:
import numpy as np
x = np.array([1,2,3,4])

y = np.array([5.5,6.5,7.5,8.5])
print(x+y)
print(x-y)
print(x*y)
print(x/y)

[ 6.5  8.5 10.5 12.5]
[-4.5 -4.5 -4.5 -4.5]
[ 5.5 13.  22.5 34. ]
[0.18181818 0.30769231 0.4        0.47058824]


In [18]:
X = np.array([[1,2], [3,4]])
print(x.mean())
print(np.median(x))
print(np.sqrt(x))
print(np.min(x,axis=0))
print(np.max(x,axis=0))
print(np.exp(x))
print(np.std(x))


2.5
2.5
[1.         1.41421356 1.73205081 2.        ]
1
4
[ 2.71828183  7.3890561  20.08553692 54.59815003]
1.118033988749895
