In [4]:
import numpy as np
x=np.array([[1,2],[3,4]])
print("1st colmn max",x[:,0].max())
print("2nd colmn max",x[:,1].max())
print("1st row max",x[0].max())
print("2nd row max",x[1].max())

1st colmn max 3
2nd colmn max 4
1st row max 2
2nd row max 4


In [5]:
x=np.array([1,2,3,4])
y=np.array([5.5,6.5,7.5,8.5])
print(x+y,x-y,x*y,x/y,sep="\n")

[ 6.5  8.5 10.5 12.5]
[-4.5 -4.5 -4.5 -4.5]
[ 5.5 13.  22.5 34. ]
[0.18181818 0.30769231 0.4        0.47058824]
